/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nygrendr' at '2/12/17 7:50 PM' with Gradle 2.13
 *
 * @author nygrendr, @date 2/12/17 7:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
